name: "flutterwave"
description: "Flutterwave official flutter library to accept payment via card, USSD, Mobile Money etc."
version: 0.0.4-null-safety
homepage: "https://github.com/Flutterwave/flutterwave-flutter"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_des: ^1.0.0
  flutter:
    sdk: flutter

  http: ^0.13.3
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.12
flutter:
  uses-material-design: true
  fonts:
    - family: FLW
      fonts:
        - asset: fonts/FLW-Regular.ttf
        - asset: fonts/FLW-Bold.ttf
