name: "flutterwave"
description: "Flutterwave official flutter library to accept payment via card, USSD, Mobile Money etc."
version: 0.1.0
homepage: "https://github.com/Flutterwave/flutterwave-flutter"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  webview_flutter: ^2.0.8
# New Encryption Plugin with null safety
  dart_3des: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  build_runner: ^2.0.4
flutter:
  uses-material-design: true
  fonts:
    - family: FLW
      fonts:
        - asset: fonts/FLW-Regular.ttf
        - asset: fonts/FLW-Bold.ttf
